name: CI/CD Pipeline with Docker Hub and AWS EC2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # 1. Build, Test, and Push Docker Image to Docker Hub
  build-test-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

      # Run tests before pushing
      - name: Run Tests Inside Docker Container
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/my-app:latest npm test

      # Push Docker image to Docker Hub if tests pass
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

  # 2. Deploy Application on EC2 Using SSH and Ansible
  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-test-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SSH into EC2 and Deploy with Ansible
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ~/my-app
            git pull
            sudo ansible-playbook ansible/playbook.yml
