name: CI/CD Pipeline with Docker Hub, Ansible & AWS EC2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build API Docker Image
      - name: Build API Docker Image
        working-directory: ./backend
        run: docker build -t jigs751/genshinappapi:1.0 .

      # Build Frontend Docker Image
      - name: Build Frontend Docker Image
        working-directory: ./frontend
        run: docker build -t jigs751/genshinapp-frontend1:1.0 .

      # Push API Image
      - name: Push API Image
        run: docker push jigs751/genshinappapi:1.0

      # Push Frontend Image
      - name: Push Frontend Image
        run: docker push jigs751/genshinapp-frontend1:1.0

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-test-and-push
    steps:
      # Checkout repository (if needed)
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Deploy with Ansible on EC2 using SSH Action
      - name: Deploy with Ansible on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/my-app
            cd ~/my-app
            # Ensure the .ssh directory exists and add GitHub's host key
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            # Clone repository using HTTPS with token authentication
            if [ ! -d .git ]; then
              git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/JigsX/GenshinApp-main-main.git .
            else
              git pull
            fi
            # Run the Ansible playbook
            ansible-playbook playbook.yml
